"""fixed name of NotificationPreferance table

Revision ID: 66b54ccba3f5
Revises: feda8d3c24ee
Create Date: 2026-01-03 23:52:48.091537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '66b54ccba3f5'
down_revision: Union[str, Sequence[str], None] = 'feda8d3c24ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferances',
    sa.Column('preferred_channed', sa.String(length=30), nullable=False),
    sa.Column('quiet_hours_start', postgresql.TIME(timezone=True), nullable=False),
    sa.Column('quiet_hours_end', postgresql.TIME(timezone=True), nullable=False),
    sa.Column('channel_specific_settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('email_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('telegram_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferances_email_enabled'), 'notification_preferances', ['email_enabled'], unique=False)
    op.create_index(op.f('ix_notification_preferances_push_enabled'), 'notification_preferances', ['push_enabled'], unique=False)
    op.create_index(op.f('ix_notification_preferances_telegram_enabled'), 'notification_preferances', ['telegram_enabled'], unique=False)
    op.create_index(op.f('ix_notification_preferances_user_id'), 'notification_preferances', ['user_id'], unique=False)
    op.drop_index(op.f('ix_notification_preferences_email_enabled'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_push_enabled'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_telegram_enabled'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('preferred_channed', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('quiet_hours_start', postgresql.TIME(timezone=True), autoincrement=False, nullable=False),
    sa.Column('quiet_hours_end', postgresql.TIME(timezone=True), autoincrement=False, nullable=False),
    sa.Column('channel_specific_settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('email_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('push_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('telegram_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notification_preferences_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notification_preferences_pkey'))
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    op.create_index(op.f('ix_notification_preferences_telegram_enabled'), 'notification_preferences', ['telegram_enabled'], unique=False)
    op.create_index(op.f('ix_notification_preferences_push_enabled'), 'notification_preferences', ['push_enabled'], unique=False)
    op.create_index(op.f('ix_notification_preferences_email_enabled'), 'notification_preferences', ['email_enabled'], unique=False)
    op.drop_index(op.f('ix_notification_preferances_user_id'), table_name='notification_preferances')
    op.drop_index(op.f('ix_notification_preferances_telegram_enabled'), table_name='notification_preferances')
    op.drop_index(op.f('ix_notification_preferances_push_enabled'), table_name='notification_preferances')
    op.drop_index(op.f('ix_notification_preferances_email_enabled'), table_name='notification_preferances')
    op.drop_table('notification_preferances')
    # ### end Alembic commands ###
