"""Initial tables

Revision ID: d210fe82d076
Revises: 
Create Date: 2025-12-30 20:22:13.473941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd210fe82d076'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_channels',
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=30), nullable=False),
    sa.Column('requires_auth', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('default_settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('type')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('channel_configs',
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('is_valid', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_visited_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('channel_type', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channel_configs_user_id'), 'channel_configs', ['user_id'], unique=False)
    op.create_table('notification_delivery_logs',
    sa.Column('notification_type', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('error_message', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('channel_type', sa.String(length=32), nullable=False),
    sa.Column('queued_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('sent_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('delievered_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_delivery_logs_user_id'), 'notification_delivery_logs', ['user_id'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('preferred_channed', sa.String(length=30), nullable=False),
    sa.Column('quiet_hours_start', postgresql.TIME(timezone=True), nullable=False),
    sa.Column('quiet_hours_end', postgresql.TIME(timezone=True), nullable=False),
    sa.Column('channel_specific_settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('email_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('telegram_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_email_enabled'), 'notification_preferences', ['email_enabled'], unique=False)
    op.create_index(op.f('ix_notification_preferences_push_enabled'), 'notification_preferences', ['push_enabled'], unique=False)
    op.create_index(op.f('ix_notification_preferences_telegram_enabled'), 'notification_preferences', ['telegram_enabled'], unique=False)
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_telegram_enabled'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_push_enabled'), table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_email_enabled'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_notification_delivery_logs_user_id'), table_name='notification_delivery_logs')
    op.drop_table('notification_delivery_logs')
    op.drop_index(op.f('ix_channel_configs_user_id'), table_name='channel_configs')
    op.drop_table('channel_configs')
    op.drop_table('users')
    op.drop_table('notification_channels')
    # ### end Alembic commands ###
