"""fixed typo in notificationpreferance

Revision ID: dc2b4fbceb16
Revises: 66b54ccba3f5
Create Date: 2026-01-04 01:41:38.036863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc2b4fbceb16'
down_revision: Union[str, Sequence[str], None] = '66b54ccba3f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_preferances', sa.Column('preferred_channel', sa.String(length=30), nullable=False))
    op.drop_column('notification_preferances', 'preferred_channed')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_preferances', sa.Column('preferred_channed', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.drop_column('notification_preferances', 'preferred_channel')
    # ### end Alembic commands ###
